CFLAGS+=-O2 -std=c11

LDADD=-lcrypto

SEDRE=-r

all: easyseed

HASHPROG=sha256sum

include Makefile.inc

easyseed: wordlist.h $(OBJS)
	cc -o $@ $(OBJS) $(LDADD)

install:
	install $(PROG) /usr/local/bin
	install $(PROG).$(MANSEC) /usr/local/man/man1
